// ============================================
// SITE_CONFIG — Configuración central de Fiesta Total DJ's
// Edita aquí todos los valores del sitio sin buscar en el código.
// ============================================

const LOGO_URL = "/media/images/public/user_69a46dc91fd9a09073ad451c/7e959c807_ChatGPTImage29abr202612_25_40.png";

export const SITE_CONFIG = {
  // === BRANDING ===
  brandName: "Fiesta Total DJ's",
  tagline: "Producción integral de eventos",
  mainPhrase: "Haz que tu evento sea inolvidable",
  secondaryPhrases: [
    "No ponemos música. Creamos momentos.",
    "Convierte tu evento en un espectáculo.",
    "Ambientes únicos, elegantes y llenos de energía.",
  ],

  // === ASSETS ===
  logoUrl: LOGO_URL,
  splashVideoUrl: "https://i.imgur.com/6vRgVCl.mp4",
  backgroundVideoUrl: "", // URL de video de fondo (dejar vacío para no usar)
  backgroundImageUrl: "", // URL de imagen de fondo
  musicUrl: "/assets/audio/fiesta-total-dj-loop.mp3", // Sube tu MP3 a /public/assets/audio/fiesta-total-dj-loop.mp3

  // === SCROLL ANIMATION ===
  // Coloca los frames HD exportados en /public/assets/scroll-sequence/
  // Ejemplo: frame_0001.jpg, frame_0002.jpg, ...
  scrollFramesBasePath: "/assets/scroll-sequence/",
  scrollFrameExtension: "jpg", // Cambiar a webp o png si prefieres
  scrollFrameCount: 180, // Número total de frames

  // === CONTACTO ===
  whatsappNumber: "55 3898 5007",
  whatsappLink: "https://wa.me/525538985007",
  whatsappDefaultMessage: "Hola%2C%20quiero%20cotizar%20Fiesta%20Total%20DJ%27s%20para%20mi%20evento.%20Me%20interesa%20recibir%20informaci%C3%B3n%20de%20paquetes.",
  email: "fiestatotaldjs@hotmail.com",
  instagram: "fiesta_total_djs",
  instagramUrl: "https://instagram.com/fiesta_total_djs",
  facebook: "DynamicSystemDjs",
  facebookUrl: "https://facebook.com/DynamicSystemDjs",
  tiktok: "fiestatotaldjs",
  tiktokUrl: "https://www.tiktok.com/@fiestatotaldjs?_r=1&_t=ZS-96Uo1gojdun",
  phone: "5538985007",

  // === SERVICIOS ===
  services: [
    {
      title: "DJ para bodas, XV años y corporativos",
      description: "Música, mezcla y ambiente adaptado al momento de tu evento.",
      icon: "Disc3",
    },
    {
      title: "Audio profesional",
      description: "Sistemas de audio potentes y claros para eventos sociales y corporativos.",
      icon: "Speaker",
    },
    {
      title: "Iluminación robótica y láser RGB",
      description: "Luces, beams, wash y efectos para transformar el ambiente.",
      icon: "Lightbulb",
    },
    {
      title: "Pistas iluminadas LED pixel",
      description: "Pistas visuales para elevar la energía del baile.",
      icon: "LayoutGrid",
    },
    {
      title: "Mega pantallas LED",
      description: "Pantallas para visuales, videos, mensajes y momentos especiales.",
      icon: "Monitor",
    },
    {
      title: "Cabina DJ iluminada",
      description: "Montaje visual con presencia profesional para el centro del show.",
      icon: "Music",
    },
    {
      title: "Shows interactivos",
      description: "Personajes, animación y momentos de alto impacto para invitados.",
      icon: "Sparkles",
    },
    {
      title: "Karaoke de cortesía",
      description: "Una experiencia extra para hacer participar a tus invitados.",
      icon: "Mic",
    },
    {
      title: "Producción integral de eventos",
      description: "Audio, iluminación, montaje y ambiente en una sola solución.",
      icon: "Zap",
    },
  ],

  // === PAQUETES ===
  packages: [
    {
      name: "Paquete Básico",
      mediaKey: "basico",
      label: "Ideal para reuniones íntimas",
      range: "30 a 50 personas",
      price: "$4,500",
      upgradeText: "+ Pista LED pixel $6,100 (16 módulos 4×4)",
      highlights: [
        "2 sistemas de audio Electro Voice o HK",
        "Cabina mampara DJ booth iluminada",
        "4 cañones RGB de luz LED",
        "Máquina de humo",
        "1 pantalla de 50 pulgadas",
        "DJ profesional con amplio repertorio",
        "5 horas de servicio",
      ],
      fullDetails: [
        "2 sistemas de audio Electro Voice o HK amplificados",
        "Cabina mampara DJ booth iluminada",
        "4 cañones RGB de luz LED baño de color",
        "2 luces sincro LED audio rítmicas con movimiento",
        "Máquina de humo",
        "1 pantalla de 50 pulgadas",
        "Una estructura para montaje",
        "DJ profesional con amplio repertorio musical",
        "Consola Yamaha",
        "Cabina DJ Pioneer",
        "Micrófono alámbrico Shure",
        "Souvenirs, globos tipo salchicha y pulseras de luz neón",
        "Karaoke de cortesía",
        "5 horas de servicio",
      ],
    },
    {
      name: "Paquete Básico Estelar",
      mediaKey: "basicoEstelar",
      label: "Más presencia para eventos pequeños y medianos",
      range: "50 a 80 personas",
      price: "$6,800",
      upgradeText: "+ Pista LED pixel $7,600 (20 módulos 4×5)",
      highlights: [
        "2 sistemas de audio Electro Voice o HK",
        "2 subwoofer Electro Voice 1500w",
        "Cabina DJ booth vintage con perimetrales",
        "2 robóticas aro LED de 200w",
        "1 pantalla de 50 pulgadas",
        "DJ profesional con amplio repertorio",
        "5 horas de servicio",
      ],
      fullDetails: [
        "2 sistemas de audio Electro Voice o HK amplificados",
        "2 subwoofer Electro Voice 1500w",
        "Cabina mampara DJ booth vintage con perimetrales",
        "4 cañones RGB de luz LED baño de color",
        "2 luces estudio RGB luz cálida",
        "2 robóticas aro LED de 200w",
        "Máquina de humo",
        "1 pantalla de 50 pulgadas",
        "2 estructuras para montaje",
        "DJ profesional con amplio repertorio musical",
        "Consola Yamaha",
        "Cabina DJ Pioneer",
        "Micrófono alámbrico Shure",
        "Souvenirs, globos tipo salchicha y pulseras de luz neón",
        "Karaoke de cortesía",
        "5 horas de servicio",
      ],
    },
    {
      name: "Paquete Medio",
      mediaKey: "medio",
      label: "Ideal para eventos con mayor energía",
      range: "100 a 150 personas",
      price: "$8,500",
      featured: true,
      upgradeText: "+ Pista LED pixel $9,500 (25 módulos 5×5)",
      highlights: [
        "4 sistemas de audio profesional",
        "2 subwoofer Electro Voice",
        "Cabina DJ booth LED pixel RGB",
        "4 cabezas beam 9R",
        "Láser RGB 3D",
        "Animación durante el evento",
        "5 horas de servicio",
      ],
      fullDetails: [
        "4 sistemas de audio profesional",
        "2 sistemas de audio medios Electro Voice",
        "2 subwoofer Electro Voice",
        "Cabina DJ booth LED pixel RGB",
        "6 cañones wash RGB de luz LED baño de color",
        "4 cabezas beam 9R",
        "1 láser RGB de 5 watts 3D",
        "2 pantallas de 50 pulgadas",
        "4 estructuras para montaje",
        "Máquina de humo",
        "Consola Yamaha",
        "Cabina DJ Pioneer",
        "DMX interface control de luces / Light Jockey / operador de luces",
        "DJ profesional con amplio repertorio musical",
        "2 micrófonos inalámbricos",
        "Animación durante el evento",
        "Show botarga inflable para batucada",
        "Souvenirs: globos, pulseras de luz neón, collares hawaianos neón",
        "Karaoke",
        "Servicio por 5 horas",
      ],
    },
    {
      name: "Paquete Completo DJ",
      mediaKey: "completoDj",
      label: "Producción completa para eventos grandes",
      range: "150 a 200 personas",
      price: "$13,500",
      upgradeText: "+ Pista LED pixel $13,700 (36 módulos 6×6 m)",
      highlights: [
        "6 sistemas medios de audio profesional",
        "4 sistemas de audio Electro Voice",
        "6 robóticas beam 9R",
        "2 láser RGB 3D",
        "Cabina DJ booth LED pixel gráfica",
        "Animador / maestro de ceremonias",
        "6 horas de servicio",
      ],
      fullDetails: [
        "6 sistemas medios de audio profesional",
        "4 sistemas de audio Electro Voice",
        "2 subwoofer dobles Melo",
        "2 pantallas de 50 pulgadas",
        "6 robóticas beam 9R",
        "8 luces PAR LED wash baño de color",
        "4 luces wash luz arquitectónica decorativa tono de luz a elegir",
        "2 láser de 5w RGB 3D",
        "Máquina de humo",
        "Interface DMX control de luces por computadora programable / Light Jockey",
        "Cabina DJ booth LED pixel gráfica",
        "DJ profesional con amplio repertorio musical",
        "Animador / maestro de ceremonias",
        "Show cabezón interactivo tipo Luis Miguel o Bad Bunny",
        "Consola Yamaha de 12 canales",
        "Controlador Mixer Pioneer DDJ 1000",
        "2 micrófonos inalámbricos Shure",
        "6 estructuras enteladas para montaje de iluminación",
        "Show interactivo inflable para batucada con diversidad de personajes",
        "Souvenirs: globos salchicha, pulseras neón, sombreros bombín, corbatas neón, collares hawaianos",
        "6 horas de servicio",
      ],
    },
    {
      name: "Paquete VIP",
      mediaKey: "vip",
      label: "Para bodas, XV años y eventos de alto impacto",
      range: "250 a 400 personas",
      price: "$19,500",
      premium: true,
      upgradeText: "+ Pista LED pixel $20,500 (54 módulos 6×9 m)",
      highlights: [
        "8 sistemas de audio profesional",
        "6 medios Electro Voice",
        "8 robóticas beam 9R",
        "3 láser RGB 3D",
        "Máquina de humo RGB",
        "Tarima 3×2 para cabina de DJ",
        "6 horas de servicio",
      ],
      fullDetails: [
        "8 sistemas de audio profesional",
        "6 medios Electro Voice",
        "2 subwoofer dobles Melo",
        "2 subwoofer individuales cubo Electro Voice",
        "4 pantallas: 2 de 42\" y 2 de 50\"",
        "8 robóticas beam 9R",
        "10 luces PAR LED wash baño de color",
        "4 luces wash luz arquitectónica decorativa",
        "3 láser de 5w RGB 3D",
        "Máquina de humo RGB",
        "Interface DMX control de luces por computadora programable / Light Jockey",
        "Cabina DJ booth LED pixel gráfica",
        "Templete tarima 3×2 para cabina de DJ y animador",
        "DJ profesional con amplio repertorio musical",
        "Animador / maestro de ceremonias",
        "Show cabezón de Bad Bunny",
        "Show cabezón Luis Miguel",
        "Show sanquero de LED",
        "Show interactivo inflable para batucada / personaje a elegir",
        "Consola Yamaha de 16 canales",
        "Controlador Mixer Pioneer DDJ 1000",
        "2 micrófonos inalámbricos Shure",
        "Estructura para montaje de iluminación tipo portería 7×4 m",
        "Iluminación arquitectónica decorativa con 4 cañones PAR LED",
        "Souvenirs: globos salchicha, pulseras neón, sombreros bombín, corbatas neón, antifaces, tubos luminosos LED",
        "6 horas de servicio",
      ],
    },
  ],

  // === EXTRAS ===
  extras: [
    {
      title: "Mega pantalla LED",
      price: "$7,500",
      description: "Pantalla LED gigante como protagonista visual de tu evento. Ideal para reproducir contenido, videos, mensajes especiales, logotipos de marca y ambientación visual de alto impacto.",
      image: "/media/images/public/69f263dc709c74ed7d2f8111/b323fdf9d_pantalla2.jpeg",
      whatsappMsg: "Hola%2C%20quiero%20cotizar%20el%20servicio%20de%20Mega%20pantalla%20LED%20para%20mi%20evento.%20%C2%BFMe%20compartes%20informaci%C3%B3n%2C%20disponibilidad%20y%20precio%3F",
    },
    {
      title: "Pista de baile LED pixel",
      price: "Desde $6,100",
      description: "Pista iluminada LED pixel que convierte el centro de tu evento en el punto visual más impactante de la noche. Disponible en distintos tamaños según el espacio y número de invitados.",
      image: "/media/images/public/69f263dc709c74ed7d2f8111/42fe3458b_pista1.jpg",
      sizes: [
        { label: "16 módulos 4×4", price: "$6,100" },
        { label: "20 módulos 4×5", price: "$7,600" },
        { label: "25 módulos 5×5", price: "$9,500" },
        { label: "36 módulos 6×6 m", price: "$13,700" },
        { label: "54 módulos 6×9 m", price: "$20,500" },
      ],
      whatsappMsg: "Hola%2C%20quiero%20cotizar%20el%20servicio%20de%20Pista%20de%20baile%20LED%20pixel%20para%20mi%20evento.%20%C2%BFMe%20compartes%20informaci%C3%B3n%2C%20disponibilidad%20y%20precio%3F",
    },
    {
      title: "Shows interactivos",
      price: "A cotizar",
      description: "Personajes, artistas y dinámicas interactivas para levantar el ambiente durante los momentos clave del evento. Sorprende a tus invitados con entretenimiento en vivo de alto impacto.",
      image: "/media/images/public/69f263dc709c74ed7d2f8111/40ea0d47f_showsinteractivos1.jpg",
      imagePosition: "center 25%",
      whatsappMsg: "Hola%2C%20quiero%20cotizar%20el%20servicio%20de%20Shows%20interactivos%20para%20mi%20evento.%20%C2%BFMe%20compartes%20informaci%C3%B3n%2C%20disponibilidad%20y%20precio%3F",
    },
    {
      title: "Iluminación arquitectónica decorativa",
      price: "A cotizar",
      description: "Baño de color y ambientación visual para transformar completamente salones, jardines y espacios interiores. Uplights, cañones PAR LED y efectos de luz que cambian la atmósfera de cualquier espacio.",
      image: "/media/images/public/69f263dc709c74ed7d2f8111/6e42a5d96_iluminacionarquitectonica1.jpg",
      whatsappMsg: "Hola%2C%20quiero%20cotizar%20el%20servicio%20de%20Iluminaci%C3%B3n%20arquitect%C3%B3nica%20decorativa%20para%20mi%20evento.%20%C2%BFMe%20compartes%20informaci%C3%B3n%2C%20disponibilidad%20y%20precio%3F",
    },
    {
      title: "Pantallas y visuales",
      price: "A cotizar",
      description: "Apoyo visual con pantallas adicionales para entradas, transmisiones en vivo, videos, branding, pistas de baile y momentos especiales a lo largo del evento.",
      image: "/media/images/public/69f263dc709c74ed7d2f8111/7afcb79d3_pantalla1.jpg",
      whatsappMsg: "Hola%2C%20quiero%20cotizar%20el%20servicio%20de%20Pantallas%20y%20visuales%20para%20mi%20evento.%20%C2%BFMe%20compartes%20informaci%C3%B3n%2C%20disponibilidad%20y%20precio%3F",
    },
    {
      title: "Show de cabezones",
      price: "A cotizar",
      description: "Personajes cabezones interactivos para animar la pista, levantar el ambiente y crear momentos divertidos durante el evento. Ideal para batucada, entradas especiales, baile y momentos de alto impacto con invitados.",
      image: "/media/images/public/69f263dc709c74ed7d2f8111/43735cb9a_Showcabezones1.jpg",
      imagePosition: "center 30%",
      variants: [
        "Cabezón Bad Bunny",
        "Cabezón Luis Miguel",
        "Personaje a elegir",
        "Otros personajes disponibles",
      ],
      whatsappMsg: "Hola%2C%20quiero%20cotizar%20el%20servicio%20de%20Show%20de%20cabezones%20para%20mi%20evento.%20%C2%BFMe%20compartes%20informaci%C3%B3n%2C%20disponibilidad%20y%20precio%3F",
    },
  ],

  // === GALERÍA ===
  galleryCategories: [
    "Todos",
    "Bodas",
    "XV años",
    "Corporativos",
    "Pistas LED",
    "Iluminación",
    "Pantallas LED",
    "Cabina DJ",
    "Shows",
  ],

  galleryItems: [
    // Bodas
    { category: "Bodas", title: "Boda elegante con pista LED", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/d09ad523b_generated_image.png" },
    { category: "Bodas", title: "Boda con iluminación premium", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/ae858f884_generated_image.png" },
    { category: "Bodas", title: "Boda con producción integral", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/81c2af6cc_generated_image.png" },
    { category: "Bodas", title: "Boda show de luces", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/6b8a45c64_generated_image.png" },
    // XV años
    { category: "XV años", title: "XV años con iluminación robótica", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/a04cf85f9_generated_image.png" },
    { category: "XV años", title: "XV años espectacular", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/1f9cb8d7e_generated_image.png" },
    { category: "XV años", title: "XV años premium", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/bf8ac9944_generated_image.png" },
    { category: "XV años", title: "XV años producción total", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/2e1c1bd91_generated_image.png" },
    // Corporativos
    { category: "Corporativos", title: "Evento corporativo premium", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/594a81be4_generated_image.png" },
    { category: "Corporativos", title: "Gala corporativa", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/652f64ba9_generated_image.png" },
    { category: "Corporativos", title: "Conferencia premium", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/a888cc059_generated_image.png" },
    { category: "Corporativos", title: "Evento empresarial élite", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/652f64ba9_generated_image.png" },
    // Pistas LED
    { category: "Pistas LED", title: "Pista LED pixel en acción", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/b4df41309_generated_image.png" },
    { category: "Pistas LED", title: "Pista LED espectacular", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/b60a67dbb_generated_image.png" },
    { category: "Pistas LED", title: "Pista LED show de colores", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/62c148bca_generated_image.png" },
    { category: "Pistas LED", title: "Pista LED evento premium", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/b4df41309_generated_image.png" },
    // Iluminación
    { category: "Iluminación", title: "Iluminación láser RGB", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/68d34b3c9_generated_image.png" },
    { category: "Iluminación", title: "Beams y efectos láser", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/5e3aafff9_generated_image.png" },
    { category: "Iluminación", title: "Cabezas robóticas en show", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/910113fec_generated_image.png" },
    { category: "Iluminación", title: "Show de iluminación premium", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/0958fa285_generated_image.png" },
    // Pantallas LED
    { category: "Pantallas LED", title: "Mega pantalla LED", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/702975b53_generated_image.png" },
    { category: "Pantallas LED", title: "Pantalla LED gran formato", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/26da4fbc2_generated_image.png" },
    { category: "Pantallas LED", title: "Video wall premium", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/5f002d24f_generated_image.png" },
    { category: "Pantallas LED", title: "Pantalla LED evento social", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/f3ba51508_generated_image.png" },
    // Cabina DJ
    { category: "Cabina DJ", title: "Cabina DJ booth iluminada", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/e080e12c1_generated_image.png" },
    { category: "Cabina DJ", title: "DJ profesional en acción", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/b46dc8829_generated_image.png" },
    { category: "Cabina DJ", title: "Cabina DJ LED pixel", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/b76215814_generated_image.png" },
    { category: "Cabina DJ", title: "Setup DJ premium", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/134881daf_generated_image.png" },
    // Shows
    { category: "Shows", title: "Show interactivo", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/ea4871961_generated_image.png" },
    { category: "Shows", title: "Animación en vivo", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/6b6f78dea_generated_image.png" },
    { category: "Shows", title: "Performers premium", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/3a609d5b3_generated_image.png" },
    { category: "Shows", title: "Show de entretenimiento élite", type: "image", url: "/media/images/public/69f263dc709c74ed7d2f8111/a1081bef1_generated_image.png" },
  ],
};